import { supabase, assertNoError } from '../config/supabase.js';

const ONE_HOUR_MS = 60 * 60 * 1000;

/** Invalidates any outstanding tokens of this purpose for the user (so
 * requesting a new reset link makes older ones stop working) and creates a
 * fresh one. Returns the DB row id only — the raw token is generated by the
 * caller and never stored. */
export async function createToken(userId, purpose, tokenHash) {
  await invalidateOutstanding(userId, purpose);
  const { data, error } = await supabase
    .from('auth_tokens')
    .insert({
      user_id: userId,
      purpose,
      token_hash: tokenHash,
      expires_at: new Date(Date.now() + ONE_HOUR_MS).toISOString(),
    })
    .select('id')
    .single();
  assertNoError(error, 'createToken');
  return data.id;
}

export async function findValidToken(tokenHash, purpose) {
  const { data, error } = await supabase
    .from('auth_tokens')
    .select('id, user_id, expires_at, used_at')
    .eq('token_hash', tokenHash)
    .eq('purpose', purpose)
    .is('used_at', null)
    .gt('expires_at', new Date().toISOString())
    .maybeSingle();
  assertNoError(error, 'findValidToken');
  return data ? { id: data.id, userId: data.user_id } : null;
}

export async function markTokenUsed(id) {
  const { error } = await supabase
    .from('auth_tokens')
    .update({ used_at: new Date().toISOString() })
    .eq('id', id);
  assertNoError(error, 'markTokenUsed');
}

export async function invalidateOutstanding(userId, purpose) {
  const { error } = await supabase
    .from('auth_tokens')
    .update({ used_at: new Date().toISOString() })
    .eq('user_id', userId)
    .eq('purpose', purpose)
    .is('used_at', null);
  assertNoError(error, 'invalidateOutstanding');
}
